import alembic.command
import click
from alembic.util import AutogenerateDiffsDetected

from app import app, db


@app.cli.group("db")
def group():
    pass


@group.command()
@click.argument("name", required=False, nargs=-1)
def migration(name=None):
    if not name:
        print("You need to provide a name for the migration")
        try:
            alembic.command.check(db.alembic_cfg)
        except AutogenerateDiffsDetected as e:
            print(e)
        return
    name = " ".join(name)
    alembic.command.revision(db.alembic_cfg, autogenerate=True, message=name)
