"""Initial db

Revision ID: 5fed6263f3a6
Revises:
Create Date: 2024-08-18 12:27:33.876662

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fed6263f3a6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column(
            "image_type",
            sa.Enum("local", "gravatar", "discord", name="imagetype"),
            nullable=False,
        ),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("discord_id", sa.String(), nullable=True),
        sa.Column("discord_access_token", sa.String(), nullable=True),
        sa.Column("discord_refresh_token", sa.String(), nullable=True),
        sa.Column("hide_in_list", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
