name: Check for linting errors

on:
  push:
    paths:
      - '**.py'
  pull_request:
    branches:
      - develop
      - release
    paths:
      - '**.py'


jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'
      - run: pip install Flake8 Flake8-pyproject black
      - run: flake8
      - run: black --check .
